# Generated by Django 3.2.2 on 2021-05-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=32)),
                ("slug", models.CharField(max_length=32, unique=True)),
                ("content", models.TextField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
